before_script:
  - "sudo pip install pgxnclient"
  - "sudo apt-get install libv8-dev"
  - "sudo pgxn install plv8"
  - "psql -c 'create database test' -U postgres"

script:
  - "TESTDBNAME=test npm run test"

notifications:
  irc: "irc.freenode.org#pgrest"

language: node_js

node_js:
  - 0.8
  - 0.9

