before_script:
  - "sudo pip install pgxnclient"
  - "sudo apt-get install libv8-dev"
  - "sudo pgxn install plv8"
  - "git clone https://bitbucket.org/adunstan/json_91.git"
  - "cd json_91; sudo make all install; cd .."
  - "createdb -U postgres test"

script:
  - "TESTDBNAME=test npm run test"

notifications:
  irc: "irc.freenode.org#pgrest"

language: node_js

node_js:
  - 0.8
  - 0.10

